version: "3"

tasks:
  default:
    desc: Run the API server in dev mode.
    summary: |
      Run the API server in development mode.

      This command will run the server in development mode and it is not
      intended to be used in other environments.
    env:
      PORT: 8080
    cmd: go run ./cmd/burzcontent/main.go

  build:
    desc: Build the executable binary.
    summary: |
      Build the executable binary for the server.

      This command will build the executable binary after compiling the Go
      source code.
    sources:
      - "*.go"
    generates:
      - ./bin/burzcontent
    cmd: go build -o bin/burzcontent ./cmd/burzcontent
